apiVersion: v1 
kind: Service
metadata:
  name: frontend-nginxapp
  labels:
    app: frontend-nginxapp
    tier: frontend
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 31234
  selector:
    app: frontend-nginxapp