apiVersion: v1 
kind: Service
metadata:
  name: usermgmt-restapp-service
spec:
  type: NodePort
  selector:
    app: usermgmt-restapp
  ports:
    - port: 8095 # service port
      targetPort: 8095 # container port
      nodePort: 31231 # node port