apiVersion: v1 
kind: Service
metadata: 
  name: mysql
  labels:
    runon: fargate 
  namespace: ns-ums
spec:
  type: ExternalName 
  externalName: usermgmtdb.cnomgyh5nvph.us-east-1.rds.amazonaws.com
